<?php
/*
 *
 * Transforms ER in XML representation to
 * equivalent Z notation in pdf.
 *
 */

// Import fpdf library
require('fpdf.php');

// Global variables
$m = 20; //margin
$h = 7; //height
$s = 10; //sangria
$state_entities = array();
$state_relationships = array();
$relationship_type = "";
$state_ids = array();
$id_null = array();
$pdf=new FPDF('P', 'mm', 'Letter');

// Show header
$pdf->SetMargins($m,$m);
$pdf->AddPage();
$pdf->SetFont('Arial','B',14);
$pdf->Write($h,'Z Notation');
$pdf->SetFont('Arial','',11);
$pdf->Ln();
$pdf->Write($h,'Generated by ERZ');

//read XML location
$xmlDoc = new DOMDocument();
$xmlDoc->load($_REQUEST['location']);

// Set type of relationship (by opposite or participation)
$x = $xmlDoc->getElementsByTagName('relation');
foreach ($x AS $item)
    $relationship_type = $item->getAttribute('relationship_type');


/*
 *
 * Show INFO scheme (entities and attributes)
 *
 */

$pdf->SetFont('Arial','B',11);
$pdf->Ln($h*2.2);
$pdf->Write($h,'Entities and attributes');
$pdf->SetFont('Arial','',11);

$entity = $xmlDoc->getElementsByTagName('entity');
foreach ($entity AS $ent){
    $pdf->Ln($h*2);
    $pdf->Write($h,'Entity: '.strtoupper($ent->getAttribute('name')));
    $pdf->Ln($h*1.25);

    // For state information
    array_push($state_entities,strtoupper($ent->getAttribute('name')));

    // Definition of data diccionary
    $inicio = true;
    $id = 0;
    $att_nulo = true;
    $attribute = $xmlDoc->getElementsByTagName('attribute');

    // Show attributes
    foreach ($attribute AS $att){
        if ($att->parentNode->parentNode->getAttribute('name')==$ent->getAttribute('name')){
            if ($inicio){
                $inicio=false;
                $pdf->Cell($s);
                $pdf->Write($h,'[');
                $pdf->Write($h,strtoupper($att->getAttribute('name')));
            }
            else $pdf->Write($h,', '.strtoupper($att->getAttribute('name')));
            if ($att->getAttribute('pk')=='true') {
                $id++;
                // For state information
                array_push($state_ids,strtolower($att->getAttribute('name')));
            }
            else $att_nulo = false;
        }
    }

    if (!$inicio) $pdf->Write($h,']');

    // Definition of INFO scheme
    $pdf->Ln($h*1.25);
    $pdf->Cell($s);

    if ($att_nulo){
        $pdf->Write($h,'NULL_'.strtoupper($ent->getAttribute('name')).' ::= no_information_'.strtolower($ent->getAttribute('name')));
        $pdf->Ln($h*1.25);
        $pdf->Cell($s);

        $x = $pdf->GetX()-1;
        $y = $pdf->GetY()+($h/2);
        if ($y>240){
            $pdf->AddPage();
            $pdf->Cell($s);
            $x = $pdf->GetX()-1;
            $y = $pdf->GetY()+($h/2);
        }
        $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()+1,$pdf->GetY()+($h/2));
        $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()-1,$pdf->GetY()+($h*1.5));
        $pdf->Write($h,'INFO_'.strtoupper($ent->getAttribute('name')));
        $pdf->Line($pdf->GetX()+1,$pdf->GetY()+($h/2),175,$pdf->GetY()+($h/2));

        $pdf->Ln();
        $pdf->Cell($s);
        $pdf->Write($h,'att_'.strtolower($ent->getAttribute('name')).': NULL_'.strtoupper($ent->getAttribute('name')));

        if ($y>$pdf->GetY()) $pdf->Line($x,20,$x,$pdf->GetY()+$h);
        else $pdf->Line($x,$y,$x,$pdf->GetY()+$h);
        $pdf->Line($x,$pdf->GetY()+$h,175,$pdf->GetY()+$h);
    }
    else{
        $x = $pdf->GetX()-1;
        $y = $pdf->GetY()+($h/2);
        if ($y>240){
            $pdf->AddPage();
            $pdf->Cell($s);
            $x = $pdf->GetX()-1;
            $y = $pdf->GetY()+($h/2);
        }
        $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()+1,$pdf->GetY()+($h/2));
        $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()-1,$pdf->GetY()+($h*1.5));
        $pdf->Write($h,'INFO_'.strtoupper($ent->getAttribute('name')));
        $pdf->Line($pdf->GetX()+1,$pdf->GetY()+($h/2),175,$pdf->GetY()+($h/2));

        $attribute = $xmlDoc->getElementsByTagName('attribute');
        foreach ($attribute AS $att){
            if (($att->parentNode->parentNode->getAttribute('name')==$ent->getAttribute('name')) && ($att->getAttribute('pk')!='true')){
                $att_nulo = false;
                $pdf->Ln();
                $pdf->Cell($s);
                $pdf->Write($h,strtolower($att->getAttribute('name')).': '.strtoupper($att->getAttribute('name')));
            }
        }
        if ($y>$pdf->GetY()) $pdf->Line($x,20,$x,$pdf->GetY()+$h);
        else $pdf->Line($x,$y,$x,$pdf->GetY()+$h);
        $pdf->Line($x,$pdf->GetY()+$h,175,$pdf->GetY()+$h);
    }
    $pdf->Ln($h*1.5);
    $pdf->Cell($s);

    if ($id==0) $pdf->Write($h,'Error: Each entity should have an id.');
    elseif ($id==1){
        // Definition of INSTA scheme
        $x = $pdf->GetX()-1;
        $y = $pdf->GetY()+($h/2);
        if ($y>240){
            $pdf->AddPage();
            $pdf->Cell($s);
            $x = $pdf->GetX()-1;
            $y = $pdf->GetY()+($h/2);
        }
        $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()+1,$pdf->GetY()+($h/2));
        $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()-1,$pdf->GetY()+($h*1.5));
        $pdf->Write($h,'INSTA_'.strtoupper($ent->getAttribute('name')));
        $pdf->Line($pdf->GetX()+1,$pdf->GetY()+($h/2),175,$pdf->GetY()+($h/2));

        $idname = '';
        $attribute = $xmlDoc->getElementsByTagName('attribute');
        foreach ($attribute AS $att){
            if (($att->parentNode->parentNode->getAttribute('name')==$ent->getAttribute('name')) && ($att->getAttribute('pk')=='true')){
                $pdf->Ln();
                $pdf->Cell($s);
                $pdf->Write($h,strtolower($att->getAttribute('name')).': ');
                $xt = $pdf->GetX();
                $yt = $pdf->GetY();
                $pdf->Image('zimg/power-s.gif',$xt+1,$yt+2);
                $pdf->SetXY($xt+3, $yt);
                $idname = strtoupper($att->getAttribute('name'));
                $pdf->Write($h,' '.$idname);
            }
        }

        $pdf->Ln();
        $pdf->Cell($s);
        $pdf->Write($h,'info_'.strtolower($ent->getAttribute('name')).': ');
        $pdf->Write($h,$idname.' ');
        $xt = $pdf->GetX();
        $yt = $pdf->GetY();
        $pdf->Image('zimg/pfun-s.gif',$xt+1,$yt+2);
        $pdf->SetXY($xt+5, $yt);
        $pdf->Write($h,'INFO_'.strtoupper($ent->getAttribute('name')));
        $pdf->Ln($h*1.2);
        $pdf->Cell($s);
        $pdf->Line($pdf->GetX()-1,$pdf->GetY(),125,$pdf->GetY());
        $pdf->Ln();
        $pdf->Cell($s);
        $pdf->Write($h,strtolower($idname).' = dom ');
        $pdf->Write($h,'info_'.strtolower($ent->getAttribute('name')));
        if ($y>$pdf->GetY()) $pdf->Line($x,20,$x,$pdf->GetY()+$h);
        else $pdf->Line($x,$y,$x,$pdf->GetY()+$h);
        $pdf->Line($x,$pdf->GetY()+$h,175,$pdf->GetY()+$h);
    }
    else $pdf->Write($h,'Warning: No multiple identifiers functionality.');
}


/*
 *
 * Show ASOCIA schemes (Relationships)
 *
 */

$pdf->SetFont('Arial','B',11);
$pdf->Ln($h*2.2);
$pdf->Write($h,'Relationships');
$pdf->SetFont('Arial','',11);
$exists_relationships = false;
$r = $xmlDoc->getElementsByTagName('relationship');
foreach ($r AS $item){
    $exists_relationships = true;
    //state information
    array_push($state_relationships,'ASOCIA_'.strtoupper($item->getAttribute('parent')).'_'.strtoupper($item->getAttribute('child')));

    $pdf->Ln($h*2);
    $pdf->Write($h,'Relationship: '.strtoupper($item->getAttribute('parent')).'-'.strtoupper($item->getAttribute('child')));
    $pdf->Ln($h*1.25);
    $pdf->Cell($s);
    $x = $pdf->GetX()-1;
    $y = $pdf->GetY()+($h/2);
    if ($y>220){
        $pdf->AddPage();
        $pdf->Cell($s);
        $x = $pdf->GetX()-1;
        $y = $pdf->GetY()+($h/2);
    }
    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()+1,$pdf->GetY()+($h/2));
    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()-1,$pdf->GetY()+($h*1.5));
    $pdf->Write($h,'ASOCIA_'.strtoupper($item->getAttribute('parent')).'_'.strtoupper($item->getAttribute('child')));
    $pdf->Line($pdf->GetX()+1,$pdf->GetY()+($h/2),175,$pdf->GetY()+($h/2));

    $idparent = '';
    $idchild = '';
    $attribute = $xmlDoc->getElementsByTagName('attribute');
    foreach ($attribute AS $att){
        if (($att->parentNode->parentNode->getAttribute('name')==$item->getAttribute('parent')) && ($att->getAttribute('pk')=='true')){

            $pdf->Ln();
            $pdf->Cell($s);
            $pdf->Write($h,strtolower($att->getAttribute('name')).': ');
            $xt = $pdf->GetX();
            $yt = $pdf->GetY();
            $pdf->Image('zimg/power-s.gif',$xt+1,$yt+2);
            $pdf->SetXY($xt+3, $yt);
            $idparent = strtoupper($att->getAttribute('name'));
            $pdf->Write($h,' '.$idparent);

            if (!in_array($idparent, $id_null)){
                if ($relationship_type=="Opposite"){
                    if (($item->getAttribute('card_parent')=='01') or ($item->getAttribute('card_parent')=='0N'))
                        array_push($id_null,$idparent);
                }
                else {
                    if (($item->getAttribute('card_child')=='01') or ($item->getAttribute('card_child')=='0N'))
                        array_push($id_null,$idparent);
                }
            }
        }
    }

    $attribute = $xmlDoc->getElementsByTagName('attribute');
    foreach ($attribute AS $att){
        if (($att->parentNode->parentNode->getAttribute('name')==$item->getAttribute('child')) && ($att->getAttribute('pk')=='true')){
            $pdf->Ln();
            $pdf->Cell($s);
            $pdf->Write($h,strtolower($att->getAttribute('name')).': ');
            $xt = $pdf->GetX();
            $yt = $pdf->GetY();
            $pdf->Image('zimg/power-s.gif',$xt+1,$yt+2);
            $pdf->SetXY($xt+3, $yt);
            $idchild = strtoupper($att->getAttribute('name'));
            $pdf->Write($h,' '.$idchild);


        }
    }

    $pdf->Ln();
    $pdf->Cell($s);
    $pdf->Write($h,'asocia_'.strtolower($item->getAttribute('parent')).'_'.strtolower($item->getAttribute('child')).': ');
    $pdf->Write($h,$idparent.' ');
    $xt = $pdf->GetX();
    $yt = $pdf->GetY();
    $pdf->Image('zimg/rel-m.gif',$xt+1,$yt+2);
    $pdf->SetXY($xt+6, $yt);
    $pdf->Write($h,$idchild);




    // restriction of cardinality by partial function
    if ($relationship_type=="Opposite"){
    //check the domain optionality
    $pdf->Ln($h*1.2);
    $pdf->Cell($s);
    $pdf->Line($pdf->GetX()-1,$pdf->GetY(),125,$pdf->GetY());
    $pdf->Ln();
    $pdf->Cell($s);
    $pdf->Write($h,'dom '.'asocia_'.strtolower($item->getAttribute('parent')).'_'.strtolower($item->getAttribute('child')).' ');
    $xt = $pdf->GetX();
    $yt = $pdf->GetY();
    if (($item->getAttribute('card_child')=="01") or ($item->getAttribute('card_child')=="0N")) $pdf->Image('zimg/subseteq-m.gif',$xt+1,$yt+2);
    else $pdf->Write($h,'=');
    $pdf->SetXY($xt+3, $yt);
    $pdf->Write($h,' '.$idparent);

    //check the range optionality
    $pdf->Ln();
    $pdf->Cell($s);
    $pdf->Write($h,'ran '.'asocia_'.strtolower($item->getAttribute('parent')).'_'.strtolower($item->getAttribute('child')).' ');
    $xt = $pdf->GetX();
    $yt = $pdf->GetY();
    if (($item->getAttribute('card_parent')=="01") or ($item->getAttribute('card_parent')=="0N")) $pdf->Image('zimg/subseteq-m.gif',$xt+1,$yt+2);
    else $pdf->Write($h,'=');
    $pdf->SetXY($xt+3, $yt);
    $pdf->Write($h,' '.$idchild);

        if ((($item->getAttribute('card_parent')=="01") or ($item->getAttribute('card_parent')=="11")) and (($item->getAttribute('card_child')=="0N") or ($item->getAttribute('card_child')=="1N") )){
            // partial or inject function, depends of cardinality
            $pdf->Ln();
            $pdf->Cell($s);
            $pdf->Write($h,'asocia_'.strtolower($item->getAttribute('parent')).'_'.strtolower($item->getAttribute('child')).' ~ ');
            $xt = $pdf->GetX();
            $yt = $pdf->GetY();
            $pdf->Image('zimg/in-m.gif',$xt+1,$yt+2);
            $pdf->SetXY($xt+5, $yt);
            $pdf->Write($h,$idchild.' ');
            $xt = $pdf->GetX();
            $yt = $pdf->GetY();
            $pdf->Image('zimg/pfun-s.gif',$xt+1,$yt+2);
            $pdf->SetXY($xt+5, $yt);
            $pdf->Write($h,$idparent);
        }
        elseif ((($item->getAttribute('card_parent')=="0N") or ($item->getAttribute('card_parent')=="1N")) and (($item->getAttribute('card_child')=="01") or ($item->getAttribute('card_child')=="11") )){
            // partial or inject function, depends of cardinality
            $pdf->Ln();
            $pdf->Cell($s);
            $pdf->Write($h,'asocia_'.strtolower($item->getAttribute('parent')).'_'.strtolower($item->getAttribute('child')).' ');
            $xt = $pdf->GetX();
            $yt = $pdf->GetY();
            $pdf->Image('zimg/in-m.gif',$xt+1,$yt+2);
            $pdf->SetXY($xt+5, $yt);
            $pdf->Write($h,$idparent.' ');
            $xt = $pdf->GetX();
            $yt = $pdf->GetY();
            $pdf->Image('zimg/pfun-s.gif',$xt+1,$yt+2);
            $pdf->SetXY($xt+5, $yt);
            $pdf->Write($h,$idchild);
        }
        elseif ((($item->getAttribute('card_parent')=="01") or ($item->getAttribute('card_parent')=="11")) and (($item->getAttribute('card_child')=="01") or ($item->getAttribute('card_child')=="11") )){
            // partial or inject function, depends of cardinality
            $pdf->Ln();
            $pdf->Cell($s);
            $pdf->Write($h,'asocia_'.strtolower($item->getAttribute('parent')).'_'.strtolower($item->getAttribute('child')).' ');
            $xt = $pdf->GetX();
            $yt = $pdf->GetY();
            $pdf->Image('zimg/in-m.gif',$xt+1,$yt+2);
            $pdf->SetXY($xt+5, $yt);
            $pdf->Write($h,$idparent.' ');
            $xt = $pdf->GetX();
            $yt = $pdf->GetY();
            $pdf->Image('zimg/pinj-s.gif',$xt+1,$yt+2);
            $pdf->SetXY($xt+5, $yt);
            $pdf->Write($h,$idchild);
        }
    }
    else{ //Relationship by Participation
    //check the domain optionality
    $pdf->Ln($h*1.2);
    $pdf->Cell($s);
    $pdf->Line($pdf->GetX()-1,$pdf->GetY(),125,$pdf->GetY());
    $pdf->Ln();
    $pdf->Cell($s);
    $pdf->Write($h,'dom '.'asocia_'.strtolower($item->getAttribute('parent')).'_'.strtolower($item->getAttribute('child')).' ');
    $xt = $pdf->GetX();
    $yt = $pdf->GetY();
    if (($item->getAttribute('card_parent')=="01") or ($item->getAttribute('card_parent')=="0N")) $pdf->Image('zimg/subseteq-m.gif',$xt+1,$yt+2);
    else $pdf->Write($h,'=');
    $pdf->SetXY($xt+3, $yt);
    $pdf->Write($h,' '.$idparent);

    //check the range optionality
    $pdf->Ln();
    $pdf->Cell($s);
    $pdf->Write($h,'ran '.'asocia_'.strtolower($item->getAttribute('parent')).'_'.strtolower($item->getAttribute('child')).' ');
    $xt = $pdf->GetX();
    $yt = $pdf->GetY();
    if (($item->getAttribute('card_child')=="01") or ($item->getAttribute('card_child')=="0N")) $pdf->Image('zimg/subseteq-m.gif',$xt+1,$yt+2);
    else $pdf->Write($h,'=');
    $pdf->SetXY($xt+3, $yt);
    $pdf->Write($h,' '.$idchild);

        if ((($item->getAttribute('card_parent')=="0N") or ($item->getAttribute('card_parent')=="1N")) and (($item->getAttribute('card_child')=="01") or ($item->getAttribute('card_child')=="11") )){
            // partial or inject function, depends of cardinality
            $pdf->Ln();
            $pdf->Cell($s);
            $pdf->Write($h,'asocia_'.strtolower($item->getAttribute('parent')).'_'.strtolower($item->getAttribute('child')).' ~ ');
            $xt = $pdf->GetX();
            $yt = $pdf->GetY();
            $pdf->Image('zimg/in-m.gif',$xt+1,$yt+2);
            $pdf->SetXY($xt+5, $yt);
            $pdf->Write($h,$idchild.' ');
            $xt = $pdf->GetX();
            $yt = $pdf->GetY();
            $pdf->Image('zimg/pfun-s.gif',$xt+1,$yt+2);
            $pdf->SetXY($xt+5, $yt);
            $pdf->Write($h,$idparent);
        }
        elseif ((($item->getAttribute('card_parent')=="01") or ($item->getAttribute('card_parent')=="11")) and (($item->getAttribute('card_child')=="0N") or ($item->getAttribute('card_child')=="1N") )){
            // partial or inject function, depends of cardinality
            $pdf->Ln();
            $pdf->Cell($s);
            $pdf->Write($h,'asocia_'.strtolower($item->getAttribute('parent')).'_'.strtolower($item->getAttribute('child')).' ');
            $xt = $pdf->GetX();
            $yt = $pdf->GetY();
            $pdf->Image('zimg/in-m.gif',$xt+1,$yt+2);
            $pdf->SetXY($xt+5, $yt);
            $pdf->Write($h,$idparent.' ');
            $xt = $pdf->GetX();
            $yt = $pdf->GetY();
            $pdf->Image('zimg/pfun-s.gif',$xt+1,$yt+2);
            $pdf->SetXY($xt+5, $yt);
            $pdf->Write($h,$idchild);
        }
        elseif ((($item->getAttribute('card_parent')=="01") or ($item->getAttribute('card_parent')=="11")) and (($item->getAttribute('card_child')=="01") or ($item->getAttribute('card_child')=="11") )){
            // partial or inject function, depends of cardinality
            $pdf->Ln();
            $pdf->Cell($s);
            $pdf->Write($h,'asocia_'.strtolower($item->getAttribute('parent')).'_'.strtolower($item->getAttribute('child')).' ');
            $xt = $pdf->GetX();
            $yt = $pdf->GetY();
            $pdf->Image('zimg/in-m.gif',$xt+1,$yt+2);
            $pdf->SetXY($xt+5, $yt);
            $pdf->Write($h,$idparent.' ');
            $xt = $pdf->GetX();
            $yt = $pdf->GetY();
            $pdf->Image('zimg/pinj-s.gif',$xt+1,$yt+2);
            $pdf->SetXY($xt+5, $yt);
            $pdf->Write($h,$idchild);
        }
    }

    if ($y>$pdf->GetY()) $pdf->Line($x,20,$x,$pdf->GetY()+$h);
    else $pdf->Line($x,$y,$x,$pdf->GetY()+$h);
    $pdf->Line($x,$pdf->GetY()+$h,175,$pdf->GetY()+$h);
}


/*
 *
 * FreeType Definitions (if exists)
 *
 */

if (!empty($id_null)){
    $pdf->Ln($h*2.2);
    $pdf->Write($h,"FreeType Definitions: ");
    $pdf->Ln($h*.5);
    $pdf->Cell($s);
    foreach ($id_null AS $id){
            $pdf->Ln($h);
            $pdf->Cell($s);
            $pdf->Write($h,'NULL_'.strtoupper($id).' ::= null_'.strtolower($id).' | n'.strtolower($id));
            $pdf->Image('zimg/ldata-m.gif',$pdf->GetX()+2,$pdf->GetY()+1);
            $pdf->Cell($s/2);
            $pdf->Write($h,strtoupper($id));
            $pdf->Image('zimg/rdata-m.gif',$pdf->GetX()+2,$pdf->GetY()+1);
    }
}



/*
 *
 * Show SYSTEM STATE scheme
 */

$pdf->SetFont('Arial','B',11);
$pdf->Ln($h*2.2);
$pdf->Write($h,'System State');
$pdf->SetFont('Arial','',11);
$pdf->Ln($h*1.5);
$pdf->Cell($s);

$x = $pdf->GetX()-1;
$y = $pdf->GetY()+($h/2);
if ($y>220){
    $pdf->AddPage();
    $pdf->Cell($s);
    $x = $pdf->GetX()-1;
    $y = $pdf->GetY()+($h/2);
}

$pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()+1,$pdf->GetY()+($h/2));
$pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()-1,$pdf->GetY()+($h*1.5));
$pdf->Write($h,'SYSTEM_STATE ');
$pdf->Line($pdf->GetX()+1,$pdf->GetY()+($h/2),175,$pdf->GetY()+($h/2));

foreach ($state_entities AS $ent){
    $pdf->Ln($h);    
    $pdf->Cell($s);
    $pdf->Write($h,"INSTA_".$ent);
}

foreach ($state_relationships AS $item){
    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,$item);

}

if ($y>$pdf->GetY()) $pdf->Line($x,20,$x,$pdf->GetY()+$h);
else $pdf->Line($x,$y,$x,$pdf->GetY()+$h);
$pdf->Line($x,$pdf->GetY()+$h,175,$pdf->GetY()+$h);

// INITIAL SYSTEM STATE
$pdf->Ln($h*1.5);
$pdf->Cell($s);

$x = $pdf->GetX()-1;
$y = $pdf->GetY()+($h/2);
if ($y>220){
    $pdf->AddPage();
    $pdf->Cell($s);
    $x = $pdf->GetX()-1;
    $y = $pdf->GetY()+($h/2);
}
$pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()+1,$pdf->GetY()+($h/2));
$pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()-1,$pdf->GetY()+($h*1.5));
$pdf->Write($h,'INITIAL_SYSTEM_STATE ');
$pdf->Line($pdf->GetX()+1,$pdf->GetY()+($h/2),175,$pdf->GetY()+($h/2));

$pdf->Ln($h);
$pdf->Cell($s);

$pdf->Write($h,"SYSTEM_STATE'");
$pdf->Ln($h*.25);
$pdf->Cell($s);
$pdf->Line($pdf->GetX()-1,$pdf->GetY()+$h,125,$pdf->GetY()+$h);

foreach ($state_ids AS $ent){
    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,$ent."'=");
    $pdf->Image('zimg/emptyset-m.gif',$pdf->GetX()+2,$pdf->GetY()+1);
}

foreach ($state_relationships AS $item){
    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,strtolower($item)."'=");
    $pdf->Image('zimg/emptyset-m.gif',$pdf->GetX()+2,$pdf->GetY()+1);
}

if ($y>$pdf->GetY()) $pdf->Line($x,20,$x,$pdf->GetY()+$h);
else $pdf->Line($x,$y,$x,$pdf->GetY()+$h);
$pdf->Line($x,$pdf->GetY()+$h,175,$pdf->GetY()+$h);




/*
 * 
 * Show OPERATION schemes
 * 
 */


/*

$pdf->SetFont('Arial','B',11);
$pdf->Ln($h*2.2);
$pdf->Write($h,'Schemes for operations');
$pdf->SetFont('Arial','',11);

foreach ($state_entities AS $ent){
    $pdf->Ln($h*1.5);
    $pdf->Cell($s);

    $x = $pdf->GetX()-1;
    $y = $pdf->GetY()+($h/2);
    if ($y>220){
        $pdf->AddPage();
        $pdf->Cell($s);
        $x = $pdf->GetX()-1;
        $y = $pdf->GetY()+($h/2);
    }

    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()+1,$pdf->GetY()+($h/2));
    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()-1,$pdf->GetY()+($h*1.5));
    $pdf->Write($h,strtoupper($ent).'_OPERATION');
    $pdf->Line($pdf->GetX()+1,$pdf->GetY()+($h/2),175,$pdf->GetY()+($h/2));

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Image('zimg/Delta-m.gif',$pdf->GetX()+2,$pdf->GetY()+1);
    $pdf->Cell($s/2);
    $pdf->Write($h,"SYSTEM_STATE");
    $pdf->SetFont('Arial','',9);

    foreach ($state_entities AS $ent1){
        if ($ent1==$ent){
            $pdf->Ln($h);
            $pdf->Cell($s);
            $pdf->Image('zimg/Xi-s.gif',$pdf->GetX()+2,$pdf->GetY()+1);
            $pdf->Cell($s/2);
            $pdf->Write($h,"SYSTEM_STATE \ (INSTA_".strtoupper($ent1).", INSTA_".strtoupper($ent1)."')");
        }
    }

    $r = $xmlDoc->getElementsByTagName('relationship');
    foreach ($r AS $item){
        if (strtoupper($item->getAttribute('parent'))==$ent){
            $pdf->Ln($h);
            $pdf->Cell($s);
            $pdf->Image('zimg/Xi-s.gif',$pdf->GetX()+2,$pdf->GetY()+1);
            $pdf->Cell($s/2);
            $pdf->Write($h,'SYSTEM_STATE \ (ASOCIA_'.strtoupper($item->getAttribute('parent')).'_'.strtoupper($item->getAttribute('child')).', ASOCIA_'.strtoupper($item->getAttribute('parent')).'_'.strtoupper($item->getAttribute('child'))."')");
        }
    }

    $pdf->SetFont('Arial','',11);

    if ($y>$pdf->GetY()) $pdf->Line($x,20,$x,$pdf->GetY()+$h);
    else $pdf->Line($x,$y,$x,$pdf->GetY()+$h);
    $pdf->Line($x,$pdf->GetY()+$h,175,$pdf->GetY()+$h);
}


*/
// OPERATIONS

    $pdf->SetFont('Arial','B',11);
    $pdf->Ln($h*2.2);
    $pdf->Write($h,'Schemas for operations');
    $pdf->SetFont('Arial','',11);


foreach ($state_entities AS $ent){
    $pdf->Ln($h*2.2);
    $pdf->Cell($s);

    $x = $pdf->GetX()-1;
    $y = $pdf->GetY()+($h/2);
    if ($y>220){
        $pdf->AddPage();
        $pdf->Cell($s);
        $x = $pdf->GetX()-1;
        $y = $pdf->GetY()+($h/2);
    }

    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()+1,$pdf->GetY()+($h/2));
    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()-1,$pdf->GetY()+($h*1.5));
    $pdf->Write($h,strtoupper($ent).'_OPERATION');
    $pdf->Line($pdf->GetX()+1,$pdf->GetY()+($h/2),175,$pdf->GetY()+($h/2));

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Image('zimg/Delta-m.gif',$pdf->GetX()+2,$pdf->GetY()+1);
    $pdf->Cell($s/2);
    $pdf->Write($h,"SYSTEM_STATE");

foreach ($state_entities AS $ent1){
    if ($ent1!=$ent){
        $pdf->Ln($h);
        $pdf->Cell($s);
        $pdf->Image('zimg/Xi-s.gif',$pdf->GetX()+2,$pdf->GetY()+1);
        $pdf->Cell($s/2);
        $pdf->Write($h,"INSTA_".strtoupper($ent1));
    }
}

$r = $xmlDoc->getElementsByTagName('relationship');
foreach ($r AS $item){
    if (strtoupper($item->getAttribute('child'))!=$ent){
        $pdf->Ln($h);
        $pdf->Cell($s);
        $pdf->Image('zimg/Xi-s.gif',$pdf->GetX()+2,$pdf->GetY()+1);
        $pdf->Cell($s/2);
        $pdf->Write($h,'ASOCIA_'.strtoupper($item->getAttribute('parent')).'_'.strtoupper($item->getAttribute('child')));
    }
}

        if ($y>$pdf->GetY()) $pdf->Line($x,20,$x,$pdf->GetY()+$h);
        else $pdf->Line($x,$y,$x,$pdf->GetY()+$h);
        $pdf->Line($x,$pdf->GetY()+$h,175,$pdf->GetY()+$h);
}




/*
 *
 * Basic Operations
 *
 */




$noresponse = true;

$pdf->SetFont('Arial','B',11);
$pdf->Ln($h*2.4);
$pdf->Write($h,'Basic Operations');
$pdf->SetFont('Arial','',11);


if ($exists_relationships){

foreach ($state_entities AS $ent){

    $pdf->Ln($h*2);
    $pdf->Write($h,'Basic Operations for '.$ent);

    $ischild = false;
    $haschild = false;
    $r = $xmlDoc->getElementsByTagName('relationship');
    foreach ($r AS $item){
        if (strtoupper($item->getAttribute('child'))==$ent) $ischild = true;
        if (strtoupper($item->getAttribute('parent'))==$ent) $haschild = true;
    }

    $id = "";
    $a = $xmlDoc->getElementsByTagName('attribute');
    foreach ($a AS $item)
        if ((strtoupper($item->parentNode->parentNode->getAttribute('name'))==$ent) && ($item->getAttribute('pk')=='true'))
            $id = $item->getAttribute('name');




    /*
     *  ADD_OK operation
     */

    $pdf->Ln($h*1.5);
    $pdf->Cell($s);


    $null_noexists = true;

    if ($ischild) $max = 140;
    else $max = 210;

    $x = $pdf->GetX()-1;
    $y = $pdf->GetY()+($h/2);
    if ($y>$max){
        $pdf->AddPage();
        $pdf->Cell($s);
        $x = $pdf->GetX()-1;
        $y = $pdf->GetY()+($h/2);
    }

    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()+1,$pdf->GetY()+($h/2));
    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()-1,$pdf->GetY()+($h*1.5));
    $pdf->Write($h,strtoupper($ent).'_ADD_OK');
    $pdf->Line($pdf->GetX()+1,$pdf->GetY()+($h/2),175,$pdf->GetY()+($h/2));

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,strtoupper($ent).'_OPERATION');

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,strtolower($id)."_in? : ".strtoupper($id));

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,'info_'.strtolower($ent).'_in? : INFO_'.strtoupper($ent));

    if (!$ischild){
        $pdf->Ln($h*.2);
        $pdf->Cell($s);
        $pdf->Line($pdf->GetX()-1,$pdf->GetY()+$h,125,$pdf->GetY()+$h);

        $pdf->Ln($h);
        $pdf->Cell($s);
        $pdf->Write($h,$id.'_in? ');
        $pdf->Image('zimg/notin-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
        $pdf->Cell($s/2);
        $pdf->Write($h,$id);

        $pdf->Ln($h);
        $pdf->Cell($s);
        $pdf->Write($h,$id."' = ".$id);
        $pdf->Image('zimg/cup-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
        $pdf->Cell($s*.6);
        $pdf->Write($h,'{'.$id.'_in?}');

        $pdf->Ln($h);
        $pdf->Cell($s);
        $pdf->Write($h,'info_'.strtolower($ent)."' = info_".strtolower($ent));
        $pdf->Image('zimg/cup-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
        $pdf->Cell($s*.6);
        $pdf->Write($h,'{'.$id.'_in?');
        $pdf->Image('zimg/mapsto-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
        $pdf->Cell($s*.6);
        $pdf->Write($h,'info_'.strtolower($ent).'_in?}');

        if ($y>$pdf->GetY()) $pdf->Line($x,20,$x,$pdf->GetY()+$h);
        else $pdf->Line($x,$y,$x,$pdf->GetY()+$h);
        $pdf->Line($x,$pdf->GetY()+$h,175,$pdf->GetY()+$h);
    }
    else{
        // la entidad participa en asociaciones como hija
        $r = $xmlDoc->getElementsByTagName('relationship');
        foreach ($r AS $re){
            if (strtoupper($re->getAttribute('child'))==$ent){
                $a = $xmlDoc->getElementsByTagName('attribute');
                foreach ($a AS $at){
                    if ((strtoupper($at->parentNode->parentNode->getAttribute('name'))==strtoupper($re->getAttribute('parent'))) && ($at->getAttribute('pk')=='true')){
                        $idparent = $at->getAttribute('name');

                        if ($relationship_type=="Opposite"){
                            if (($re->getAttribute('card_parent')=='01') or ($re->getAttribute('card_parent')=='0N')){
                                $idparent = strtoupper('NULL_'.$idparent);
                                $null_noexists = false;
                            }
                        }
                        else {
                            if (($re->getAttribute('card_child')=='01') or ($re->getAttribute('card_child')=='0N')){
                                $idparent = strtoupper('NULL_'.$idparent);
                                $null_noexists = false;
                            }
                        }

                        $pdf->Ln($h);
                        $pdf->Cell($s);
                        $pdf->Write($h,strtolower($idparent)."_in? : ".strtoupper($idparent));
                    }
                }
            }
        }

        $pdf->Ln($h*.2);
        $pdf->Cell($s);

        $pdf->Line($pdf->GetX()-1,$pdf->GetY()+$h,125,$pdf->GetY()+$h);

        $pdf->Ln($h);
        $pdf->Cell($s);
        $pdf->Write($h,$id.'_in? ');
        $pdf->Image('zimg/notin-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
        $pdf->Cell($s/2);
        $pdf->Write($h,$id);

        $r = $xmlDoc->getElementsByTagName('relationship');
        foreach ($r AS $re){
            if (strtoupper($re->getAttribute('child'))==$ent){
                $a = $xmlDoc->getElementsByTagName('attribute');

                foreach ($a AS $at){

                    if ((strtoupper($at->parentNode->parentNode->getAttribute('name'))==strtoupper($re->getAttribute('parent'))) && ($at->getAttribute('pk')=='true')){
                        $idparent = $at->getAttribute('name');
                        if ($relationship_type=="Opposite"){
                            if (($re->getAttribute('card_parent')=='01') or ($re->getAttribute('card_parent')=='0N')){
                                $idparent = strtoupper('NULL_'.$idparent);
                                $null_noexists = false;
                            }
                        }
                        else {
                            if (($re->getAttribute('card_child')=='01') or ($re->getAttribute('card_child')=='0N')){
                                $idparent = strtoupper('NULL_'.$idparent);
                                $null_noexists = false;
                            }
                        }

                        if ($null_noexists){
                            $pdf->Ln($h);
                            $pdf->Cell($s);
                            $pdf->Write($h,strtolower($idparent)."_in? ");
                            $pdf->Image('zimg/in-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
                            $pdf->Cell($s/2);
                            $pdf->Write($h,strtolower($idparent));
                        }
                    }
                }
            }
        }


        $pdf->Ln($h);
        $pdf->Cell($s);
        $pdf->Write($h,$id."' = ".$id);
        $pdf->Image('zimg/cup-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
        $pdf->Cell($s*.6);
        $pdf->Write($h,'{'.$id.'_in?}');

        $pdf->Ln($h);
        $pdf->Cell($s);
        $pdf->Write($h,'info_'.strtolower($ent)."' = info_".strtolower($ent));
        $pdf->Image('zimg/cup-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
        $pdf->Cell($s*.6);
        $pdf->Write($h,'{'.$id.'_in?');
        $pdf->Image('zimg/mapsto-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
        $pdf->Cell($s/2);
        $pdf->Write($h,'info_'.strtolower($ent).'_in?}');


        $r = $xmlDoc->getElementsByTagName('relationship');
        foreach ($r AS $re){
            if (strtoupper($re->getAttribute('child'))==$ent){
                $connect_simple=true;
                $idparent = "";
                $parent = strtoupper($re->getAttribute('parent'));
                $a = $xmlDoc->getElementsByTagName('attribute');
                foreach ($a AS $at)
                    if ((strtoupper($at->parentNode->parentNode->getAttribute('name'))==$parent) && ($at->getAttribute('pk')=='true')){
                        $idparent = $at->getAttribute('name');
                        $idparent_old = $idparent;
                        if ($relationship_type=="Opposite"){
                            if (($re->getAttribute('card_parent')=='01') or ($re->getAttribute('card_parent')=='0N')){
                                $idparent = strtoupper('NULL_'.$idparent);
                                $connect_simple =false;
                            }
                        }
                        else {
                            if (($re->getAttribute('card_child')=='01') or ($re->getAttribute('card_child')=='0N')){
                                $idparent = strtoupper('NULL_'.$idparent);
                                $connect_simple =false;
                            }
                        }
                    }

                $pdf->Ln($h);
                $pdf->Cell($s);
                
                if ($connect_simple){
                    $asocia = "asocia_".strtolower($parent)."_".strtolower($ent);
                    $pdf->Write($h,$asocia."' = ".$asocia);
                    $pdf->Image('zimg/cup-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
                    $pdf->Ln($h);
                    $pdf->Cell(2*$s);
                    $pdf->Write($h,'{'.strtolower($idparent).'_in?');
                    $pdf->Image('zimg/mapsto-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
                    $pdf->Cell($s/2);
                    $pdf->Write($h,strtolower($id).'_in?}');
                }
                else{
                    $pdf->Write($h,'(( '.strtolower($idparent).'_in?');
                    $pdf->Image('zimg/neq-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
                    $pdf->Cell($s/2);
                    $pdf->Write($h,strtolower($idparent));
                    $pdf->Image('zimg/land-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
                    $pdf->Cell($s/2);

                    $pdf->Ln($h);
                    $pdf->Cell(2*$s);
                    $pdf->Write($h,"n".strtolower($idparent_old)." ~ ".strtolower($idparent)."_in? ");
                    $pdf->Image('zimg/in-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
                    $pdf->Cell($s/2);
                    $pdf->Write($h,strtoupper($idparent_old));
                    $pdf->Image('zimg/land-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);

                    $pdf->Ln($h);
                    $pdf->Cell(2*$s);
                    $asocia = "asocia_".strtolower($parent)."_".strtolower($ent);
                    $pdf->Write($h,$asocia."' = ".$asocia);
                    $pdf->Image('zimg/cup-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
                    $pdf->Ln($h);
                    $pdf->Cell(2*$s);
                    $pdf->Write($h,'{n'.strtolower($idparent_old)." ~ ".strtolower($idparent).'_in?');
                    $pdf->Image('zimg/mapsto-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
                    $pdf->Cell($s/2);
                    $pdf->Write($h,strtolower($id).'_in?} )');
                    $pdf->Ln($h);
                    $pdf->Cell(2*$s);
                    $pdf->Image('zimg/lor-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
                    $pdf->Cell($s/2);
                    $pdf->Write($h,$asocia."' = ".$asocia.' )');                                    
                }
            }
        }
        if ($y>$pdf->GetY()) $pdf->Line($x,20,$x,$pdf->GetY()+$h);
        else $pdf->Line($x,$y,$x,$pdf->GetY()+$h);
        $pdf->Line($x,$pdf->GetY()+$h,175,$pdf->GetY()+$h);
    }


    /*
     *  DELETE_OK operation
     */

    $pdf->Ln($h*1.5);
    $pdf->Cell($s);

    if ($ischild) $max = 200;
    else $max = 210;

    $x = $pdf->GetX()-1;
    $y = $pdf->GetY()+($h/2);
    if ($y>$max){
        $pdf->AddPage();
        $pdf->Cell($s);
        $x = $pdf->GetX()-1;
        $y = $pdf->GetY()+($h/2);
    }

    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()+1,$pdf->GetY()+($h/2));
    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()-1,$pdf->GetY()+($h*1.5));
    $pdf->Write($h,strtoupper($ent).'_DELETE_OK');
    $pdf->Line($pdf->GetX()+1,$pdf->GetY()+($h/2),175,$pdf->GetY()+($h/2));

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,strtoupper($ent).'_OPERATION');

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,strtolower($id)."_in? : ".strtoupper($id));

    $pdf->Ln($h*.2);
    $pdf->Cell($s);
    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+$h,125,$pdf->GetY()+$h);

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,$id.'_in? ');
    $pdf->Image('zimg/in-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
    $pdf->Cell($s/2);
    $pdf->Write($h,$id);

    if ($haschild){
        $r = $xmlDoc->getElementsByTagName('relationship');
        foreach ($r AS $re){
            if (strtoupper($re->getAttribute('parent'))==$ent){
                $child = strtoupper($re->getAttribute('child'));
                $pdf->Ln($h);
                $pdf->Cell($s);
                $pdf->Write($h,$id.'_in? ');
                $pdf->Image('zimg/notin-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
                $pdf->Cell($s/2);
                $pdf->Write($h," dom asocia_".strtolower($ent)."_".strtolower($child));
            }
        }
    }

    if ($ischild){
        $r = $xmlDoc->getElementsByTagName('relationship');
        foreach ($r AS $re){
            if (strtoupper($re->getAttribute('child'))==$ent){
                $parent = strtoupper($re->getAttribute('parent'));
                $pdf->Ln($h);
                $pdf->Cell($s);
                $asocia = "asocia_".strtolower($parent)."_".strtolower($ent);
                $pdf->Write($h,$asocia."' = ");
                $pdf->Write($h,$asocia);
                $pdf->Image('zimg/nrres-s.gif',$pdf->GetX()+2,$pdf->GetY()+2);
                $pdf->Cell($s/2);
                $pdf->Write($h,'{'.$id.'_in?}');
            }
        }
    }

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,'info_'.strtolower($ent)."' = ");
    $pdf->Write($h,'{'.$id.'_in?}');
    $pdf->Image('zimg/ndres-s.gif',$pdf->GetX()+2,$pdf->GetY()+2);
    $pdf->Cell($s/2);
    $pdf->Write($h,'info_'.strtolower($ent));

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,$id."' = ".$id.' \ {'.$id.'_in?}');
    
    if ($y>$pdf->GetY()) $pdf->Line($x,20,$x,$pdf->GetY()+$h);
    else $pdf->Line($x,$y,$x,$pdf->GetY()+$h);
    $pdf->Line($x,$pdf->GetY()+$h,175,$pdf->GetY()+$h);


    /*
     *  UPDATE_OK operation
     */

    $pdf->Ln($h*1.5);
    $pdf->Cell($s);

    if ($ischild) $max = 200;
    else $max = 220;

    $x = $pdf->GetX()-1;
    $y = $pdf->GetY()+($h/2);
    if ($y>$max){
        $pdf->AddPage();
        $pdf->Cell($s);
        $x = $pdf->GetX()-1;
        $y = $pdf->GetY()+($h/2);
    }

    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()+1,$pdf->GetY()+($h/2));
    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()-1,$pdf->GetY()+($h*1.5));
    $pdf->Write($h,strtoupper($ent).'_UPDATE_OK');
    $pdf->Line($pdf->GetX()+1,$pdf->GetY()+($h/2),175,$pdf->GetY()+($h/2));

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,strtoupper($ent).'_OPERATION');

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,strtolower($id)."_in? : ".strtoupper($id));
    
    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,'info_'.strtolower($ent).'_in? : INFO_'.strtoupper($ent));


    if (!$ischild){

        $pdf->Ln($h*.2);
        $pdf->Cell($s);
        $pdf->Line($pdf->GetX()-1,$pdf->GetY()+$h,125,$pdf->GetY()+$h);

        $pdf->Ln($h);
        $pdf->Cell($s);
        $pdf->Write($h,$id.'_in? ');
        $pdf->Image('zimg/in-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
        $pdf->Cell($s/2);
        $pdf->Write($h,$id);

        $pdf->Ln($h);
        $pdf->Cell($s);
        $pdf->Write($h,'info_'.strtolower($ent)."' = info_".strtolower($ent));
        $pdf->Image('zimg/oplus-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
        $pdf->Cell($s/2);
        $pdf->Write($h,'{'.$id.'_in?');
        $pdf->Image('zimg/mapsto-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
        $pdf->Cell($s/2);
        $pdf->Write($h,'info_'.strtolower($ent).'_in?}');
    }
    else{
        // la entidad tiene asociaciones como hija
        $pdf->Ln($h*.2);
        $pdf->Cell($s);

        $pdf->Line($pdf->GetX()-1,$pdf->GetY()+$h,125,$pdf->GetY()+$h);

        $pdf->Ln($h);
        $pdf->Cell($s);
        $pdf->Write($h,$id.'_in? ');
        $pdf->Image('zimg/in-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
        $pdf->Cell($s/2);
        $pdf->Write($h,$id);

        $pdf->Ln($h);
        $pdf->Cell($s);
        $pdf->Write($h,'info_'.strtolower($ent)."' = info_".strtolower($ent));
        $pdf->Image('zimg/oplus-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
        $pdf->Cell($s/2);
        $pdf->Write($h,'{'.$id.'_in?');
        $pdf->Image('zimg/mapsto-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
        $pdf->Cell($s/2);
        $pdf->Write($h,'info_'.strtolower($ent).'_in?}');

        $r = $xmlDoc->getElementsByTagName('relationship');
        foreach ($r AS $re){
            if (strtoupper($re->getAttribute('child'))==$ent){
                $parent = strtoupper($re->getAttribute('parent'));
                $pdf->Ln($h);
                $pdf->Cell($s);
                $asocia = "asocia_".strtolower($parent)."_".strtolower($ent);
                $pdf->Write($h,$asocia."' = ".$asocia);
            }
        }


    }
    if ($y>$pdf->GetY()) $pdf->Line($x,20,$x,$pdf->GetY()+$h);
    else $pdf->Line($x,$y,$x,$pdf->GetY()+$h);
    $pdf->Line($x,$pdf->GetY()+$h,175,$pdf->GetY()+$h);

    /*
     *  QUERY_OK operation
     */

    $pdf->Ln($h*1.5);
    $pdf->Cell($s);

    $max = 220;

    $x = $pdf->GetX()-1;
    $y = $pdf->GetY()+($h/2);
    if ($y>$max){
        $pdf->AddPage();
        $pdf->Cell($s);
        $x = $pdf->GetX()-1;
        $y = $pdf->GetY()+($h/2);
    }

    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()+1,$pdf->GetY()+($h/2));
    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()-1,$pdf->GetY()+($h*1.5));
    $pdf->Write($h,strtoupper($ent).'_QUERY_OK');
    $pdf->Line($pdf->GetX()+1,$pdf->GetY()+($h/2),175,$pdf->GetY()+($h/2));

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Image('zimg/Xi-s.gif',$pdf->GetX()+1,$pdf->GetY()+1);
    //$pdf->Cell($s*.2);
    $pdf->Write($h,"   SYSTEM_STATE");

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,strtolower($id)."_in? : ".strtoupper($id));

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,'info_'.strtolower($ent).'_out! : INFO_'.strtoupper($ent));

    $pdf->Ln($h*.2);
    $pdf->Cell($s);
    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+$h,125,$pdf->GetY()+$h);

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,$id.'_in? ');
    $pdf->Image('zimg/in-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
    $pdf->Cell($s/2);
    $pdf->Write($h,$id);

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,'info_'.strtolower($ent)."_out! = info_".strtolower($ent));
    $pdf->Write($h,'('.$id.'_in?)');

    if ($y>$pdf->GetY()) $pdf->Line($x,20,$x,$pdf->GetY()+$h);
    else $pdf->Line($x,$y,$x,$pdf->GetY()+$h);
    $pdf->Line($x,$pdf->GetY()+$h,175,$pdf->GetY()+$h);


    /*
     * Show Responses
     */

    $pdf->Ln($h*2.2);
    $pdf->Write($h,"Response Messages:");

    // Response
    if ($noresponse){
        $pdf->Ln($h*1.25);
        $pdf->Cell($s);
        $pdf->Write($h,"RESPONSE ::= OK | EXISTS | NOT_FOUND | HAS_RELATIONSHIPS");
        $noresponse = false;
    

    // Successful Response
    $pdf->Ln($h*1.5);
    $pdf->Cell($s);
    $x = $pdf->GetX()-1;
    $y = $pdf->GetY()+($h/2);
    if ($y>240){
        $pdf->AddPage();
        $pdf->Cell($s);
        $x = $pdf->GetX()-1;
        $y = $pdf->GetY()+($h/2);
    }
    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()+1,$pdf->GetY()+($h/2));
    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()-1,$pdf->GetY()+($h*1.5));
    $pdf->Write($h,'SUCCESS_OP');
    $pdf->Line($pdf->GetX()+1,$pdf->GetY()+($h/2),175,$pdf->GetY()+($h/2));

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,'response! : RESPONSE');

    $pdf->Ln($h*.2);
    $pdf->Cell($s);
    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+$h,125,$pdf->GetY()+$h);

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,'response! = OK');

    if ($y>$pdf->GetY()) $pdf->Line($x,20,$x,$pdf->GetY()+$h);
    else $pdf->Line($x,$y,$x,$pdf->GetY()+$h);
    $pdf->Line($x,$pdf->GetY()+$h,175,$pdf->GetY()+$h);

    }
    // Entity Error
    $pdf->Ln($h*1.5);
    $pdf->Cell($s);
    $x = $pdf->GetX()-1;
    $y = $pdf->GetY()+($h/2);
    if ($y>240){
        $pdf->AddPage();
        $pdf->Cell($s);
        $x = $pdf->GetX()-1;
        $y = $pdf->GetY()+($h/2);
    }
    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()+1,$pdf->GetY()+($h/2));
    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()-1,$pdf->GetY()+($h*1.5));
    $pdf->Write($h,$ent.'_ERROR ');
    $pdf->Line($pdf->GetX()+1,$pdf->GetY()+($h/2),175,$pdf->GetY()+($h/2));

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Image('zimg/Xi-s.gif',$pdf->GetX()+1,$pdf->GetY()+1);
    $pdf->Write($h,"   SYSTEM_STATE");

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,strtolower($id)."_in? : ".strtoupper($id));

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,'response! : RESPONSE');

    if ($y>$pdf->GetY()) $pdf->Line($x,20,$x,$pdf->GetY()+$h);
    else $pdf->Line($x,$y,$x,$pdf->GetY()+$h);
    $pdf->Line($x,$pdf->GetY()+$h,175,$pdf->GetY()+$h);



    // INSTANCE EXISTS
    $pdf->Ln($h*1.5);
    $pdf->Cell($s);
    $x = $pdf->GetX()-1;
    $y = $pdf->GetY()+($h/2);
    if ($y>230){
        $pdf->AddPage();
        $pdf->Cell($s);
        $x = $pdf->GetX()-1;
        $y = $pdf->GetY()+($h/2);
    }
    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()+1,$pdf->GetY()+($h/2));
    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()-1,$pdf->GetY()+($h*1.5));
    $pdf->Write($h,$ent.'_EXISTS ');
    $pdf->Line($pdf->GetX()+1,$pdf->GetY()+($h/2),175,$pdf->GetY()+($h/2));

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,$ent.'_ERROR ');

    $pdf->Ln($h*.2);
    $pdf->Cell($s);
    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+$h,125,$pdf->GetY()+$h);

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,$id.'_in? ');
    $pdf->Image('zimg/in-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
    $pdf->Cell($s/2);
    $pdf->Write($h,$id);

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,'response! = EXISTS');

    if ($y>$pdf->GetY()) $pdf->Line($x,20,$x,$pdf->GetY()+$h);
    else $pdf->Line($x,$y,$x,$pdf->GetY()+$h);
    $pdf->Line($x,$pdf->GetY()+$h,175,$pdf->GetY()+$h);


    // INSTANCE NOT FOUND
    $pdf->Ln($h*1.5);
    $pdf->Cell($s);
    $x = $pdf->GetX()-1;
    $y = $pdf->GetY()+($h/2);
    if ($y>230){
        $pdf->AddPage();
        $pdf->Cell($s);
        $x = $pdf->GetX()-1;
        $y = $pdf->GetY()+($h/2);
    }
    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()+1,$pdf->GetY()+($h/2));
    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()-1,$pdf->GetY()+($h*1.5));
    $pdf->Write($h,$ent.'_NOT_FOUND ');
    $pdf->Line($pdf->GetX()+1,$pdf->GetY()+($h/2),175,$pdf->GetY()+($h/2));

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,$ent.'_ERROR ');

    $pdf->Ln($h*.2);
    $pdf->Cell($s);
    $pdf->Line($pdf->GetX()-1,$pdf->GetY()+$h,125,$pdf->GetY()+$h);

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,$id.'_in? ');
    $pdf->Image('zimg/notin-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
    $pdf->Cell($s/2);
    $pdf->Write($h,$id);

    $pdf->Ln($h);
    $pdf->Cell($s);
    $pdf->Write($h,'response! = NOT_FOUND');

    if ($y>$pdf->GetY()) $pdf->Line($x,20,$x,$pdf->GetY()+$h);
    else $pdf->Line($x,$y,$x,$pdf->GetY()+$h);
    $pdf->Line($x,$pdf->GetY()+$h,175,$pdf->GetY()+$h);



    // INSTANCE HAS RELATIONSHIPS

    if ($haschild){
        $pdf->Ln($h*1.5);
        $pdf->Cell($s);
        $x = $pdf->GetX()-1;
        $y = $pdf->GetY()+($h/2);
        if ($y>230){
            $pdf->AddPage();
            $pdf->Cell($s);
            $x = $pdf->GetX()-1;
            $y = $pdf->GetY()+($h/2);
        }
        $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()+1,$pdf->GetY()+($h/2));
        $pdf->Line($pdf->GetX()-1,$pdf->GetY()+($h/2),$pdf->GetX()-1,$pdf->GetY()+($h*1.5));
        $pdf->Write($h,$ent.'_HAS_RELATIONSHIPS ');
        $pdf->Line($pdf->GetX()+1,$pdf->GetY()+($h/2),175,$pdf->GetY()+($h/2));

        $pdf->Ln($h);
        $pdf->Cell($s);
        $pdf->Write($h,$ent.'_ERROR ');

        $pdf->Ln($h*.2);
        $pdf->Cell($s);
        $pdf->Line($pdf->GetX()-1,$pdf->GetY()+$h,125,$pdf->GetY()+$h);

        $inicio = true;
        $r = $xmlDoc->getElementsByTagName('relationship');
        foreach ($r AS $re){
            if (strtoupper($re->getAttribute('parent'))==$ent){
                if ($inicio) $inicio = false;
                else $pdf->Image('zimg/land-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
                $child = strtoupper($re->getAttribute('child'));
                $pdf->Ln($h);
                $pdf->Cell($s);
                $pdf->Write($h,'('.$id.'_in? ');
                $pdf->Image('zimg/in-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
                $pdf->Cell($s/2);
                $pdf->Write($h," dom asocia_".strtolower($ent)."_".strtolower($child));
                $pdf->Image('zimg/land-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
                $pdf->Ln($h);
                $pdf->Cell($s*2);
                $pdf->Write($h,'response! = HAS_RELATIONSHIPS)');
            }
        }

        if ($y>$pdf->GetY()) $pdf->Line($x,20,$x,$pdf->GetY()+$h);
        else $pdf->Line($x,$y,$x,$pdf->GetY()+$h);
        $pdf->Line($x,$pdf->GetY()+$h,175,$pdf->GetY()+$h);
    }



}



/*
 *
 * Final Schemas
 *
 */


$pdf->SetFont('Arial','B',11);
$pdf->Ln($h*2.4);
$pdf->Write($h,'Complete Operations');
$pdf->SetFont('Arial','',11);


foreach ($state_entities AS $ent){

    $pdf->Ln($h*2);
    $pdf->Write($h,'Complete operations for '.$ent);

    $ischild = false;
    $haschild = false;
    $r = $xmlDoc->getElementsByTagName('relationship');
    foreach ($r AS $item){
        if (strtoupper($item->getAttribute('child'))==$ent) $ischild = true;
        if (strtoupper($item->getAttribute('parent'))==$ent) $haschild = true;
    }

    $id = "";
    $a = $xmlDoc->getElementsByTagName('attribute');
    foreach ($a AS $item)
        if ((strtoupper($item->parentNode->parentNode->getAttribute('name'))==$ent) && ($item->getAttribute('pk')=='true'))
            $id = $item->getAttribute('name');


    $pdf->Ln($h*1.25);
    $pdf->Cell($s);
    $x = $pdf->GetX()-1;
    $y = $pdf->GetY()+($h/2);
    if ($ischild) $max = 240;
    else $max = 250;
    if ($y>$max){
        $pdf->AddPage();
        $pdf->Cell($s);
        $x = $pdf->GetX()-1;
        $y = $pdf->GetY()+($h/2);
    }
    $pdf->Write($h,$ent.'_ADD');
    $pdf->Image('zimg/defs-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
    $pdf->Cell($s/2);
    $pdf->Write($h,'('.$ent.'_ADD_OK');
    $pdf->Image('zimg/land-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
    $pdf->Cell($s/2);
    $pdf->Write($h,'SUCCESS_OP)');
    $pdf->Ln($h);
    $pdf->Cell($s*4);
    $pdf->Image('zimg/lor-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
    $pdf->Cell($s/2);
    $pdf->Write($h,$ent.'_EXISTS');
    if ($ischild){
        $r = $xmlDoc->getElementsByTagName('relationship');
        foreach ($r AS $re){
            if (strtoupper($re->getAttribute('child'))==$ent){
                $pdf->Ln($h);
                $pdf->Cell($s*4);
                $pdf->Image('zimg/lor-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
                $pdf->Cell($s/2);
                $pdf->Write($h,strtoupper($re->getAttribute('parent')).'_NOT_FOUND');
            }
        }
    }



    $pdf->Ln($h*1.25);
    $pdf->Cell($s);
    $x = $pdf->GetX()-1;
    $y = $pdf->GetY()+($h/2);
    if ($y>250){
        $pdf->AddPage();
        $pdf->Cell($s);
        $x = $pdf->GetX()-1;
        $y = $pdf->GetY()+($h/2);
    }
    $pdf->Write($h,$ent.'_DELETE');
    $pdf->Image('zimg/defs-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
    $pdf->Cell($s/2);
    $pdf->Write($h,'('.$ent.'_DELETE_OK');
    $pdf->Image('zimg/land-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
    $pdf->Cell($s/2);
    $pdf->Write($h,'SUCCESS_OP)');
    $pdf->Ln($h);
    $pdf->Cell($s*4);
    $pdf->Image('zimg/lor-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
    $pdf->Cell($s/2);
    $pdf->Write($h,$ent.'_NOT_FOUND');
    if ($haschild){
        $pdf->Ln($h);
        $pdf->Cell($s*4);
        $pdf->Image('zimg/lor-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
        $pdf->Cell($s/2);
        $pdf->Write($h,$ent.'_HAS_RELATIONSHIPS');
    }

    $pdf->Ln($h*1.25);
    $pdf->Cell($s);
    $x = $pdf->GetX()-1;
    $y = $pdf->GetY()+($h/2);
    if ($y>250){
        $pdf->AddPage();
        $pdf->Cell($s);
        $x = $pdf->GetX()-1;
        $y = $pdf->GetY()+($h/2);
    }
    $pdf->Write($h,$ent.'_UPDATE');
    $pdf->Image('zimg/defs-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
    $pdf->Cell($s/2);
    $pdf->Write($h,'('.$ent.'_UPDATE_OK');
    $pdf->Image('zimg/land-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
    $pdf->Cell($s/2);
    $pdf->Write($h,'SUCCESS_OP)');
    $pdf->Ln($h);
    $pdf->Cell($s*4);
    $pdf->Image('zimg/lor-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
    $pdf->Cell($s/2);
    $pdf->Write($h,$ent.'_NOT_FOUND');



    $pdf->Ln($h*1.25);
    $pdf->Cell($s);
    $x = $pdf->GetX()-1;
    $y = $pdf->GetY()+($h/2);
    if ($y>250){
        $pdf->AddPage();
        $pdf->Cell($s);
        $x = $pdf->GetX()-1;
        $y = $pdf->GetY()+($h/2);
    }
    $pdf->Write($h,$ent.'_QUERY');
    $pdf->Image('zimg/defs-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
    $pdf->Cell($s/2);
    $pdf->Write($h,'('.$ent.'_QUERY_OK');
    $pdf->Image('zimg/land-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
    $pdf->Cell($s/2);
    $pdf->Write($h,'SUCCESS_OP)');
    $pdf->Ln($h);
    $pdf->Cell($s*4);
    $pdf->Image('zimg/lor-m.gif',$pdf->GetX()+2,$pdf->GetY()+2);
    $pdf->Cell($s/2);
    $pdf->Write($h,$ent.'_NOT_FOUND');


}


}
else{
    $pdf->Ln($h*2);
    $pdf->Cell($s);
    $pdf->Write($h,'Error: No relationships.');


}


// Show PDF
$pdf->Output();


?>
     