<?php
/*
 *
 * Transforms ER in XML representation to
 * equivalent Z notation in pdf.
 *
 */


//$xmlDoc->load($_REQUEST['location']);
$tex = "documentstyle[fuzz]{article}\r\n";
$tex.= "\\begin{document}\r\n";


// Global variables
$m = 20; //margin
$h = 7; //height
$s = 10; //sangria
$state_entities = array();
$state_relationships = array();
$relationship_type = "";
$state_ids = array();
$id_null = array();

// Show header
$tex .= 'Z Notation\n';
$text .= 'Generated by ERZ\n';

//read XML location
$xmlDoc = new DOMDocument();
$xmlDoc->load($_REQUEST['location']);

// Set type of relationship (by opposite or participation)
$x = $xmlDoc->getElementsByTagName('relation');
foreach ($x AS $item)
    $relationship_type = $item->getAttribute('relationship_type');


/*
 *
 * Show INFO scheme (entities and attributes)
 *
 */

$tex .='Entities and attributes\\n';

$entity = $xmlDoc->getElementsByTagName('entity');
foreach ($entity AS $ent){
    $tex .= 'Entity: '.strtoupper($ent->getAttribute('name')).'\n';

    // For state information
    array_push($state_entities,strtoupper($ent->getAttribute('name')));

    // Definition of data diccionary
    $inicio = true;
    $id = 0;
    $att_nulo = true;
    $attribute = $xmlDoc->getElementsByTagName('attribute');

    // Show attributes
    foreach ($attribute AS $att){
        if ($att->parentNode->parentNode->getAttribute('name')==$ent->getAttribute('name')){
            if ($inicio){
                $inicio=false;
                $tex .= '\\begin{zed}\n';
                $tex .= '['.strtoupper($att->getAttribute('name'));
            }
            else $tex .= ', '.strtoupper($att->getAttribute('name'));
            if ($att->getAttribute('pk')=='true') {
                $id++;
                // For state information
                array_push($state_ids,strtolower($att->getAttribute('name')));
            }
            else $att_nulo = false;
        }
    }

    if (!$inicio) $tex .= ']\n\\end{zed}\n';

}

$html = str_replace("\r\n","<br>",$tex);
echo $html;

$file = fopen('spec.tex', 'w');
fwrite($file,$tex);
fclose($file);

echo '<META HTTP-EQUIV=Refresh CONTENT=0;URL="spec.tex">';

?>